In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
dataset = pd.read_csv('data_coba.csv', delimiter=';')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
print (x)

[['France' 40.0 45000.0]
 ['Spain' 56.0 56000.0]
 ['Germany' nan 33000.0]
 ['France' 34.0 18000.0]
 ['Spain' 24.0 31000.0]
 ['France' 55.0 nan]
 ['Germany' 35.0 22000.0]
 ['France' 70.0 42000.0]]


In [13]:
print (y)

['No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes']


In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [16]:
print (x)

[['France' 40.0 45000.0]
 ['Spain' 56.0 56000.0]
 ['Germany' 44.857142857142854 33000.0]
 ['France' 34.0 18000.0]
 ['Spain' 24.0 31000.0]
 ['France' 55.0 35285.71428571428]
 ['Germany' 35.0 22000.0]
 ['France' 70.0 42000.0]]


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [19]:
print (x)

[[1.0 0.0 0.0 40.0 45000.0]
 [0.0 0.0 1.0 56.0 56000.0]
 [0.0 1.0 0.0 44.857142857142854 33000.0]
 [1.0 0.0 0.0 34.0 18000.0]
 [0.0 0.0 1.0 24.0 31000.0]
 [1.0 0.0 0.0 55.0 35285.71428571428]
 [0.0 1.0 0.0 35.0 22000.0]
 [1.0 0.0 0.0 70.0 42000.0]]


In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print(y)

[0 1 0 1 1 0 0 1]


In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [23]:
print (x_train)

[[0.0 0.0 1.0 56.0 56000.0]
 [0.0 1.0 0.0 35.0 22000.0]
 [1.0 0.0 0.0 40.0 45000.0]
 [0.0 0.0 1.0 24.0 31000.0]
 [1.0 0.0 0.0 34.0 18000.0]
 [1.0 0.0 0.0 55.0 35285.71428571428]]


In [24]:
print (x_test)

[[1.0 0.0 0.0 70.0 42000.0]
 [0.0 1.0 0.0 44.857142857142854 33000.0]]


In [25]:
print (y_train)

[1 0 0 1 1 0]


In [26]:
print (y_test)

[1 0]


In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [30]:
print(x_train)

[[0.0 0.0 1.0 1.3317957046133195 1.6503021735709569]
 [0.0 1.0 0.0 -0.4921853690962265 -0.9652710826547104]
 [1.0 0.0 0.0 -0.057904161070144115 0.8040872965567704]
 [0.0 0.0 1.0 -1.4476040267536079 -0.27291345600673966]
 [1.0 0.0 0.0 -0.579041610701443 -1.2729855833871417]
 [1.0 0.0 0.0 1.2449394630081032 0.05678065192086522]]


In [31]:
print (x_test)

[[1.0 0.0 0.0 2.5477830870863505 0.5733014210074469]
 [0.0 1.0 0.0 0.3639690124409071 -0.11905620564052394]]
